pipeline {
    // Trabalhamos com um agente global
    agent {
        docker {
            image 'node:6-alpine'
            // passa parâmetros para o container
            args '-p 3000:3000'
        }
    }
    // Defino uma variável de ambiente
    environment {
        CI = true
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
//         stage('Deliver') {
//             steps {
//                 sh './jenkins/scripts/deliver.sh'
//                 input message: 'Finished using the web site? (Click "Proceed" to continue)'
//                 sh './jenkins/scripts/kill.sh'
//             }
//         }
    }
}
